name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "linux", build-dir: "build-linux", toolchain-file: "" }
          - {
              os: "windows",
              build-dir: "build-windows",
              toolchain-file: "mingw_toolchain.cmake",
            }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Install LLVM-MinGW
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20231003/llvm-mingw-20231003-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar xf llvm-mingw-20231003-ucrt-ubuntu-20.04-x86_64.tar.xz
          mv llvm-mingw-20231003-ucrt-ubuntu-20.04-x86_64 llvm-mingw
          echo "$(pwd)/llvm-mingw/bin" >> $GITHUB_PATH
      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libboost-all-dev
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: ./${{ matrix.config.build-dir }}
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Create Build Directory, Change to it, Run CMake and Build with Make
        run: |
          mkdir -p ${{ matrix.config.build-dir }}
          cd ${{ matrix.config.build-dir }}
          cmake .. -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_TOOLCHAIN_FILE=../${{ matrix.config.toolchain-file }}
          make -j$(nproc)
      - name: List Build Results
        run: |
          echo "${{ matrix.config.os }} build results:"
          ls ${{ matrix.config.build-dir }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.os }}-build-artifacts
          path: ./${{ matrix.config.build-dir }}/main*
